---
# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.3'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -coverprofile=coverage.out -v ./...

    - name: Convert coverage to badge
      run: |
        pip install coverage-badge
        coverage-badge -o coverage.svg -i coverage.out
      shell: python

    - name: Commit coverage badge
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add coverage.svg
        git commit -m 'Add coverage badge'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
