---
# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.3'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -coverprofile=coverage.out -v ./...

    - name: Setup python
      uses: actions/setup-python@v1

    - name: Install pip dependencies
      uses: BSFishy/pip-action@v1
      with:
        packages: |
          coverage-badge
    - name: Generate coverage badge
      run: |
        coverage-badge -o coverage.svg -i coverage.out
      shell: python

    - name: Commit coverage badge
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add coverage.svg
        git commit -m 'Add coverage badge'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
